### ISSUE TITLE
KLC F5.1 & F5.2 - Is Pin1 mark required for non polarized components?

### ISSUE THREAD

**Issue by cpresser** [KiCad/kicad-website#422]
Came up while working on https://github.com/KiCad/kicad-footprints/pull/1650
Point 6 and 7 should not apply for non-polarized components.
There is actually an example picture of a THT-Resistor that does not conform to the rules the way they are currently written.

I suggest to rework Point 6:

6.  Pin-1 designator is provided on the F.SilkS layer
  a. Pin-1 designator must be visible after board assembly
  b. non-polarized components (Resistor, Fuse, ...) should not have a Pin-1 designator

What do you think?
Should we clarify that most inductors are polarized components?
F5.2 has a similar issue since it does not mention non-polarized components.

**Comment by poeschlr** [comment]
Isn't that easier solved by renaming it to polarity marker? This would also more closely fit IPC nomenclature. We could then state that the polarity marker typically marks pin 1.

A related question is: should asymmetrical parts get a polarity mark? To which i would answer yes as it aids in debug capabilities.

**Comment by cpresser** [comment]
Perhaps a native english speaker can help here.
I don't feel(!) that a CPU in TQFP-Package or a Molex-PicoBlade-Connector connector is polarized. "Pin-1 designator" sounds way better to me for those components.

Even if we choose 'polarity marker' that still does not answer which parts do get a polarity marker. Who gets to judge what is polarized and what not?
On the other hand, converging towards IPC sounds good.

As for asymmetrical parts: should the orientation not already be visible in the Fab layer? I can't really imagine a part that has this issue. Do you have an example?

**Comment by poeschlr** [comment]
Asymmetrical parts get the marker for debugging reasons. This is simply how we always did it and i see no reason not do. The only parts that do not get one are non polarized symmetrical parts. (So two terminal passives like resistors, inductors, ... As well as things like resistor arrays and the standard 4 pin buttons.)

We should at least mention that IPC calls it a polarity marker such that people who search for that can find it.
